# Generated by Django 2.2.5 on 2019-09-26 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorial_tutorial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 14, 9, 47, 557175), verbose_name='date published'),
        ),
    ]
